# PRE-REQUISITES
# setup deploy: password: secure: option below by installing ruby and travis gem and 
# executing the following from a command line in the directory where .travis.yml exists
# travis encrypt --add deploy.password <pypi password here>
language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: true
deploy:
  provider: pypi
  user: abalogh
  password:
    secure: DgrASl8bWu9TFgIYbNc4GnTCTd9BPTQQhs0fYM2TdSbsmg7IPOYC+wSwx6XVwiqs4OdG8Ngkz9IyrFXeNN1WSGJkj0+h/yzR+unhQvnmcyXiziqD7Qwbd+qNKxDL2MGlrfybxStSMt9p8+A5TC5yBKlpI6rWw/KkuwOgV/z0AV/mGFcb3z6gqSzjxYSzQ0bT6XCQRA+KpPYpDvOjM8HnKwZT3DZzTZpFyulLRXF2ZB+B/ftM+c9c4Q6OGqb1eKmd3AJStpsh56FYk3ENvELvXhXssMcDHofJzUR+js8VbmqKG1yXXQMYnzC7JCPtKdByPPDmuccmNvNlUfWkPjmP/DiHZyb8ridEjEAyA3yiF8UhwQxRX/+2/B8Nv2VMehCURljAMYQpB/JQv398URpVqWMnDuQ2RAoiQSDV+3CQx6OPx39y33OMFvuE//jvh0rOGlwVkpSRXUAZSD4Ud7YRSBVcHz+vcMfCfHk+/sSNzblWih2GOIh1Tdlxy23evDqTNqLR80IaBIgzBTGmefpL5PgVQoUCEc0O3vPSn/GIXg/onIFrfnAd4XW8VMO3+IFdtRsJ3HZRVEhv1ydhOS1Cl2rCBmM6vNquYYKdEyEAqcYkmIEnxVBs7nEsdEL01Y5w+zTpL5oX4L3Y2DrCP3DCtYgbmAtppXREHvYH/TRwni4=
  on:
    tags: true
    branch: master
