language: python
python:
- '2.7'
- nightly
install:
- pip install -r requirements.txt
script: true
deploy:
  provider: pypi
  user: abalogh
  password:
    secure: Tum8+ItAsK5ETZHs08BwMCc/unt3/aKHXJdKdmHC9WTGpLRh+OdU5NBgqTei8EOjv11PTNrTxefaBb5pq7d4zPSqDGFJvumAfXy3I4uYkdAeK8bmucQN3ZW7nkAvyTcAm+EXmBUhVDtAB0nIT2/BpRqWbJlMwnmyEvi5+bRU1VoFAqJ4xzZdoMdL5qPD0N1pER+LwS1YIrN2bLAuKdeJGq5xWhgLx/ErApIQ1xAa0wPKDZeNayrVGs7/DYk7pw2lR7Xrb1Me+CPxByMUstWEp5kUd0zUcN52gNVWvlTFdeTXfZNhHFNfqPfMg+1N49EEqeyg7c5PBXxMCVvLXbpwsckmc0tnfPRDv/JeyX3lzSaQmVA2K/uQfswKgAZ54c+d1MM5LUsT9Ok/Ah+vHiW2I6wUaSzE3nbRnAmqlhdVnu8kTBNJrnXbxVpDHQvpet5MUYz/gjvoAXgRCO3nrpJwmYZJJu+UvxNH+MDemhJ6Jry32p5K31UgMvNtel86A31/4LcrHyFbhc05EXEqRHlEWiZE25dxlCe8D5yr9WzT4qYa6xVBTsV4a3FPAbNDSmfpIM4TCrlNciycEX17/RLTVU+t6KB1Va3zUj5awNIQkndUsGozWGcd+bxOV0b59VlB+qHl83BKp2KNGtnKd6B6g32vzFrh2Rs6yw6Ohs7kGFc=
  on:
    tags: true
    branch: master
